### PR TITLE
Vacuum gripper

### PR DESCRIPTION
**Pull request by patorrad**
Added (2) packages and code for new vacuum gripper.

### CODE REVIEW

**Comment by Soofiyan** [comment]
@nickswalker please merge this request. I have incorporated the latest changes that will be utilized in the upcoming evaluation.

**Comment by nickswalker** [comment]
@JackLowry any luck with rebasing this? Otherwise I can look this afternoon

**Comment by JackLowry** [comment]
I was waiting for Soofiyan to commit the extra changes he just mentioned; I'll get do this today.

**Comment by JackLowry** [comment]
Merge with rebase in #25

**Pull request closed without merging**
